version: "3.9"

networks:
  monitor-net:
    driver: bridge

services:
 prometheus:
    image: prom/prometheus:latest
    networks:
      - monitor-net
    container_name: prometheus-container
    volumes:
      - ./prometheus/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
    ports:
      - "9090:9090"
    restart: always

 grafana:
    image: grafana/grafana-oss:latest
    user: "$UID:$GID"
    networks:
      - monitor-net
    container_name: grafana-container
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SERVER_DOMAIN=localhost
