scrape_configs:
  - job_name: 'Spring Boot Application prometheus' # Job to scrape Prometheus metrics
    scrape_interval: 3s
    static_configs:
      - targets: [ 'localhost:9090' ]
  - job_name: 'Spring Boot Application actuator' # Job to scrape application metrics
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: [ '192.168.3.8:8080' ]
        labels:
          application: 'com-smarttrader-price-history-service-stresstest'
          group: 'com-smarttrader-price-history-group'

